# VECTORS

**Objectives**:
- Understand the concept of vectors and their properties.
- Perform vector operations such as addition, subtraction, and scalar multiplication.
- Calculate the magnitude and direction of a vector.
- Understand the concept of linear combinations and linear independence

#1.1 Definition of vectors
A Vector in Python is simply a one-dimensional array of lists.

We use numpy.array() method to create vector

In [2]:
import numpy as np
myList = [1, 2, 3]
myVector = np.array(myList)

print("Let's see what our vector looks like: ")
print(myVector)

Let's see what our vector looks like: 
[1 2 3]


Vectors can be horizontal or vertical. In the next code block, you can see the difference between the appearance of these vectors



In [3]:
horizontalVector = np.array([1, 2, 3, 4])
verticalVector = np.array([[1],[2],[3],[4]])

print("Horizontal Vector created from list: ")
print(horizontalVector)
print()

print("Vertical Vector created from list: ")
print(verticalVector)

Horizontal Vector created from list: 
[1 2 3 4]

Vertical Vector created from list: 
[[1]
 [2]
 [3]
 [4]]



#1.2 Vector operations



Numpy arrays (vectors) can be operated upon by the following operations. Some of these operations are:
 - Addition
 - Subtraction
 - Multiplication
 - Division
 - Dot Product

#### Addition
The addition operation takes place in an element-wise manner i.e. element by element. As a result, the resultant vector would have the same length as that of the two additive vectors

In [4]:
# Addition
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
sum = vec1+vec2
print(sum)

[11 22 33 44 55]


#### Subtraction
Similarly, the element-wise fashion would be followed in subtraction as well. The elements of vector 2 will get subtracted from vector 1.


In [5]:
# Subtraction
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
sub = vec1-vec2
print(sub)

[ 9 18 27 36 45]


#### Multiplication
In a vector multiplication, the elements of vector 1 get multiplied by the elements of vector 2 in an element-wise manner and the product vector is of the same length as of the multiplying vectors.
In the code block below, for example, we can see that

**mul[0] = vec1[0] * vec2[0]**

**mul[1] = vec1[1] * vec2[1]**

and so on...


In [6]:
# Multiplication
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
mul = vec1*vec2
print(mul)

[ 10  40  90 160 250]


#### Division
Similar to vector multiplication, in vector division, the resultant vector is the quotient values after carrying out element-by-element division operation on the two vectors
In the code block below, for example, we can see that

**div[0] = vec1[0] / vec2[0]**

**div[1] = vec1[1] / vec2[1]**

and so on...


In [7]:
# Division
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,4,4,4,5])
div = vec1/vec2
print(div)

[10.   5.   7.5 10.  10. ]


#### Operations with Scalers
All the mentioned operations can be done using scalers too. In that case, the scaler will be iterated over all the elements of the vector

In [8]:
# Operations using Scaler
vec = np.array([1,2,3,4,5])
scaler = 5

print(scaler*vec)

[ 5 10 15 20 25]


#### Vector Dot Product
In a vector dot product, we perform the summation of the product of the two vectors in an element-wise fashion. As a result, the resultant is not a vector, but a scalar value


In [9]:
# Vector Dot Product
vec1 = np.array([1,3,5,7,9])
vec2 = np.array([1,1,1,1,1])
dotProduct = vec1.dot(vec2)
print(dotProduct)

25


# 1.3 Magnitude and direction

The magnitude of a vector is the square root of sum of element-wise squares of values in the vector. A simple way to find this would be to take the square root of the dot product of a vector with itself.

In [10]:
# Magnitude of Vector
from math import sqrt
vec = np.array([3,4])
dotProd = vec.dot(vec)
magnitude = sqrt(dotProd)

print(f"Magnitude of the vector: {vec} is {magnitude}")

Magnitude of the vector: [3 4] is 5.0


A unit vector in the direction of the vector can be found out by dividing the vector by the magnitude of the vector.

In [11]:
# direction of the vector
vec = np.array([3,4])
magnitude = sqrt(vec.dot(vec))

unitVec = vec/magnitude
print(f"Unit vector in the direction of the vector: {vec} is {unitVec}")

Unit vector in the direction of the vector: [3 4] is [0.6 0.8]


# 1.4 Linear combinations and linear independence

A linear combination of two (or more) vectors is the vector obtained by adding the vectors after multiplying them by scalar values.

In [12]:
# Linear Combinations
vec1 = np.array([1,2])
vec2 = np.array([3,1])

s1 = int(input("Input the scaler with which to multiply the first vector: "))
s2 = int(input("Input the scaler with which to multiply the second vector: "))

resultant = vec1*s1 + vec2*s2

print(f"{vec1} * {s1} + {vec2} * {s2} = {resultant}")

Input the scaler with which to multiply the first vector: 4
Input the scaler with which to multiply the second vector: 2
[1 2] * 4 + [3 1] * 2 = [10 10]


2. Linear Independence:
Let's consider two vectors a = (1, 3) and b = (2, 6). To check if these vectors are linearly independent, we need to see if there are any non-zero scalars x and y such that:
x * a + y * b = 0
Let's try to find such scalars:
x * (1, 3) + y * (2, 6) = (0, 0)
(1x + 2y, 3x + 6y) = (0, 0)
From the first component, we have:
1x + 2y = 0 => x = -2y
From the second component, we have:
3x + 6y = 0
Substituting x = -2y, we get:
3(-2y) + 6y = 0 => -6y + 6y = 0
Since the equation is true for any value of y, we can choose y = 1, which gives us x = -2. Therefore, we have: -2 * (1, 3) + 1 * (2, 6) = (0, 0)

In [13]:
# importing the numpy library
import numpy as np

### 2.1 Definition of Matrices
A Matrix is a 2-Dimensional Array comprising of rows and columns

In [15]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matrix Scalar Operations
1. Addition
2. Subtraction
3. Multiplication
4. Division

In [16]:
# addition: a constant is added to every element of the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = 10 + A
print(R)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
# subtraction: a constant is subtracted from every element of the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A - 10
print(R)

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [18]:
# multiplication: a constant is multiplied to every element of the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A * -2
print(R)

[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [19]:
# division: a constant is divided from every element of the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A / 10
print(R)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


### 2.3 Matrix Arithmetic Operations
1. Addition
2. Subtraction
3. Multiplication
4. Division

In [20]:
# two matrices are added where each element is the sum of elements at the corresponding positions
# both matrices should be of the same dimensions
# the resulting matrice is of the same dimension as its constituents
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A + B
print(R)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [21]:
# two matrices are subtracted where each element is the differnce of elements at the corresponding positions
# both matrices should be of the same dimensions
# the resulting matrice is of the same dimension as its constituents
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
R = A - B
print(R)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# two matrices are multiplied where each element is the product of elements at the corresponding positions
# both matrices should be of the same dimensions
# the resulting matrice is of the same dimension as its constituents
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A * B
print(R)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [23]:
# two matrices are subtracted where each element is the division of elements at the corresponding positions
# both matrices should be of the same dimensions
# the resulting matrice is of the same dimension as its constituents
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
R = A / B
print(R)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 2.4 Matrix Multiplication
Matrix multiplication is an operation performed on two matrices to produce a new matrix. The operation involves multiplying corresponding elements of each row of the first matrix by the corresponding elements of each column of the second matrix and adding the results.

A is a matrix of dimensions m x n, B is a matrix of dimensions n x p.

    R[i][j] = Sum(A[i][k]*B[k][j]) where k varies from 1 to n

The resulting matrix has the same number of rows as the first matrix and the same number of columns as the second matrix. The number of columns in the first matrix must be equal to the number of rows in the second matrix for matrix multiplication to be possible.

Matrix multiplication is not commutative, meaning the order of the matrices matters. That is, the product of matrix A and matrix B is not necessarily equal to the product of matrix B and matrix A.

In [24]:
A = np.array([[ 2, 4, 6], [8, 10, 12]])
B = np.array([[3, 7, 0], [8, 0, -2], [0, -4, -5]])
R = np.matmul(A, B)
print(R)

[[ 38 -10 -38]
 [104   8 -80]]


### 2.5 Determinant
In linear algebra, the determinant is a scalar value that can be computed from a square matrix. The determinant of a matrix is a mathematical tool that can be used to determine whether the matrix has an inverse, among other things.

The determinant is computed by performing a series of mathematical operations on the matrix. Specifically, the determinant of an n x n matrix A is defined as:

det(A) = sum over all permutations of the product of the sign of the permutation and the product of the elements of A corresponding to that permutation.

In simpler terms, this means that you take all possible ways to reorder the rows and columns of the matrix, multiply the elements in the diagonal, and sum or subtract them depending on the parity of the permutation.

For example, for a 2x2 matrix A = [[a, b], [c, d]], the determinant is given by:

det(A) = ad - bc.

The determinant can be used to test if a matrix is invertible or singular, to compute the eigenvalues of a matrix, to solve systems of linear equations, and more.

In [25]:
A = np.array([[3, 7, 0], [8, 0, -2], [0, -4, -5]])
D = np.linalg.det(A)
print(round(D))

256


### 2.6 Matrix Rank
The rank of a matrix is a fundamental concept in linear algebra that measures the dimension of the vector space spanned by its rows or columns. It is defined as the maximum number of linearly independent rows or columns in the matrix.

More formally, the rank of an m x n matrix A is the dimension of the vector space spanned by the rows or the columns of A. If the rows of A are linearly independent, then the rank of A is equal to the number of rows. If the columns of A are linearly independent, then the rank of A is equal to the number of columns.

The rank of a matrix has many important applications in linear algebra and other fields. For example, the rank of a matrix can be used to determine whether a system of linear equations has a unique solution, or to find the dimension of the solution space. If the rank of the coefficient matrix is less than the rank of the augmented matrix, then the system of equations has no solution. If the ranks are equal and equal to the number of variables, then the system has a unique solution.

The rank of a matrix is also closely related to the determinant of the matrix. Specifically, a matrix is invertible if and only if its determinant is nonzero, which is equivalent to its rank being equal to its size.

In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = np.linalg.matrix_rank(A)
print(rank)

2


# Transpose of a Matrix

**Objectives**:
- Understand the concept of matrix transpose and its properties.
- Calculate the transpose of a matrix.


# 3.1 What is matrix transpose?

The transpose of a matrix is an operation that flips the matrix over its diagonal. The transpose of a matrix A is denoted by A^T and is obtained by reflecting the elements of A across its diagonal.

Formally, if A is an m × n matrix, then its transpose A^T is an n × m matrix such that the element at the ith row and jth column of A is the element at the jth row and ith column of A^T, that is,

`(A^T)[i][j] = A[j][i]`

# 3.2 Properties of Transpose



1.   `[MT]T = M`

  The transpose of a transpose of a matrix is the matrix itself
2.   `(aM)T = aMT`

  If there’s a scalar a, then the transpose of the matrix M times the scalar (a) is equal to the constant times the transpose of the matrix M
3. `(M + N)T = MT + NT`

  The sum of transposes of matrices is equal to the transpose of the sum of two matrices

4. `(MN)T = NT MT`

  The product of the transposes of two matrices in reverse order is equal to the transpose of the product of them



# 3.3 Calculate the transpose of a matrix

In [27]:
import numpy as np

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the transpose of the matrix
transpose_matrix = np.transpose(matrix)

transpose_of_transpose = np.transpose(transpose_matrix)

print("Original matrix:\n", matrix)
print("Transpose matrix:\n", transpose_matrix)
print("Transpose of transpose matrix:\n", transpose_of_transpose)

Original matrix:
 [[1 2]
 [3 4]]
Transpose matrix:
 [[1 3]
 [2 4]]
Transpose of transpose matrix:
 [[1 2]
 [3 4]]


### 4.1 What is Matrix Inverse?
The inverse of a square matrix A is another matrix A^-1 that, when multiplied by A, gives the identity matrix I.

More formally, for a square matrix A, its inverse A^-1 is defined as:

A * A^-1 = A^-1 * A = I

where I is the identity matrix of the same size as A.

Not all square matrices have inverses, and a square matrix A has an inverse if and only if its determinant is nonzero. In that case, the inverse can be found using a formula that involves the determinant and the adjugate (also known as the classical adjoint) of A.

The adjugate of a matrix A, denoted adj(A), is the transpose of the matrix of cofactors of A, where the cofactor of an element a_ij is (-1)^(i+j) times the determinant of the submatrix obtained by deleting the i-th row and j-th column of A.

The formula for the inverse of A is then:

A^-1 = (1/det(A)) * adj(A)

where det(A) is the determinant of A.

The inverse of a matrix has many important applications, such as solving systems of linear equations, finding eigenvectors and eigenvalues, and diagonalizing matrices.

### 4.2 Properties of Matrix Inverse
1. If A is an invertible matrix, then its inverse A^-1 is unique.
2. If A and B are invertible matrices of the same size, then AB is invertible and (AB)^-1 = B^-1 * A^-1.
3. If A is an invertible matrix, then (A^-1)^-1 = A.
4. If A is an invertible matrix, then the transpose of A, denoted A^T, is invertible, and (A^T)^-1 = (A^-1)^T.
5. If A is an invertible matrix and c is a nonzero scalar, then the matrix cA is invertible and (cA)^-1 = (1/c) * A^-1.
6. If A is an invertible matrix and k is a positive integer, then A^k is invertible and (A^k)^-1 = (A^-1)^k.
7. If A is a symmetric positive definite matrix, then it is invertible and its inverse is also symmetric positive definite.

These properties are useful in many areas of mathematics, including linear algebra, differential equations, optimization, and statistics.

### 4.3 Calculating the inverse of a Matrix

In [28]:
import numpy as np
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
AInv = np.linalg.inv(A)
print(AInv)

LinAlgError: Singular matrix

# Dot Product Of Matrices
The dot product of two matrices A and B is defined as the sum of the products of corresponding elements of the matrices.

To find the dot product of two matrices, we first need to ensure that their dimensions are compatible. Specifically, the number of columns of matrix A must be equal to the number of rows of matrix B. If this condition is satisfied, then we can compute the dot product of A and B as follows:

1. Create a new matrix C with dimensions (m x p), where m is the number of rows of A and p is the number of columns of B.

2. For each element in the resulting matrix C, compute the dot product of the corresponding row of A and column of B.

3. To compute the dot product, multiply each corresponding pair of elements in the row and column, and then sum the products.

4. Place the resulting sum in the corresponding element of matrix C.

In [29]:
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[2,2,2],[2,2,2],[2,2,2]])


print(f"Matrix 1 : \n{matrix1}\n Matrix 2: \n{matrix2}\n")

dotProduct = matrix1.dot(matrix2)
print(f"Dot Product of the two matrices: \n{dotProduct}")

Matrix 1 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 Matrix 2: 
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Dot Product of the two matrices: 
[[12 12 12]
 [30 30 30]
 [48 48 48]]


# Eigenvalues and Eigenvectors
An eigenvector of a matrix A is a nonzero vector x that, when multiplied by A, results in a scalar multiple of x. This scalar multiple is called the eigenvalue corresponding to the eigenvector x. Mathematically, we can represent this as:

A x = λ x

where λ is the eigenvalue and x is the eigenvector.

In [30]:
import numpy as np

A = np.mat([[3,2],[1,0]])
print("A: \n", A)

eigenvalue, eigenvector = np.linalg.eig(A)

print("First tuple of eig: ", eigenvalue)
print("Second tuple of eig: \n", eigenvector)

A: 
 [[3 2]
 [1 0]]
First tuple of eig:  [ 3.56155281 -0.56155281]
Second tuple of eig: 
 [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


Eigenvalues and eigenvectors are important in many areas of mathematics and science, and have numerous applications in physics, engineering, and computer science. Some of the key properties of eigenvalues and eigenvectors include:

 - If A is an n × n matrix, then it has n eigenvalues and n corresponding eigenvectors (not necessarily distinct).

 - If A is a symmetric matrix, then its eigenvalues are real and its eigenvectors are orthogonal.

 - If A is a real matrix, then its complex eigenvalues occur in complex conjugate pairs, and its eigenvectors may have complex entries.

 - The product of the eigenvalues of A is equal to the determinant of A.

 - If A is invertible, then its eigenvectors form a basis for the vector space on which A acts.

 - The trace of A (i.e., the sum of its diagonal entries) is equal to the sum of its eigenvalues.

Eigenvalues and eigenvectors are used in a variety of applications, such as solving systems of differential equations, diagonalizing matrices, and performing spectral analysis. They are also important in machine learning and data analysis, where they are used for dimensionality reduction and clustering.